// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/details/[id].tsx";
import * as $4 from "./routes/docs/index.tsx";
import * as $5 from "./routes/github/[username].tsx";
import * as $6 from "./routes/github/_middleware.ts";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/TopWelcom.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/details/[id].tsx": $3,
    "./routes/docs/index.tsx": $4,
    "./routes/github/[username].tsx": $5,
    "./routes/github/_middleware.ts": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/TopWelcom.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
